### PR TITLE
added new command line option to be quiet

### PR DESCRIPTION
**Pull request by m-31**
... because it looks nicer in our shell output if we can silence the unimportant output

### CODE REVIEW

**Comment by felixb** [comment]
I like the idea very much. But I don't like leaking the config into all the methods.

What do you think of something like a `Printer` which can be configured to print or not print stuff?

**Comment by m-31** [comment]
> What do you think of something like a `Printer` which can be configured to print or not print stuff?
Yep. I just tried to use a logger (like logrus) for "quietable" output. This is a quite quiet change...
(I still have to take a look at the travis failures...)

**Comment by felixb** [comment]
That looks quite nice. Is `Printer` written by yourself or copied from somewhere else?

**Comment by m-31** [comment]
The use of logrus is a bit too heavy and cumbersome. So I wrote a new printer source file. Does this meet your expectations?

**Comment by felixb** [comment]
That's exactly, what I had in mind with my first comment.
I'd like you to remove all the unused methods, though. Like `SetOff` and `Printf` for the default printer.

**Comment by m-31** [comment]
I removed some unused methods,  but I am unsure about printer.Println - what do you think?

**Pull request closed without merging**
